### PR TITLE
typo: at line 387, 195, and 239

### PR DESCRIPTION
**Pull request by itsKevin-lgy**
fix #71 

fix skip spaces typo `resoled` at line 387 to `resolved`
fix skip spaces typo `thisis` at line 195 to `this is`
fix extra letter typo `prgoblem` at line 239 to `problem`

学号：52265903005 51255903055 51255903042

### CODE REVIEW

**Review by TieWay59 — APPROVED** [review]
LGTM🎉

**Review by TieWay59 — CHANGES_REQUESTED** [review]
存在冲突。

**Comment by itsKevin-lgy** [comment]
conflicts fixed!

**Review by TieWay59 — APPROVED** [review]

**Review by TieWay59 — CHANGES_REQUESTED** [review]
再次遇到冲突

**Comment by itsKevin-lgy** [comment]
> 再次遇到冲突

Sorry for the conflict again. At noon on April 18th, we checked the typo that needed to be revised, but submitted PR at 4 pm, which caused a conflict.
conflicts fixed! Thanks

**Review by TieWay59 — APPROVED** [review]

**Comment by TieWay59** [comment]
I suppose you should include five typo fixes in your PR statements.

 https://github.com/X-lab2017/oss101/pull/107/files#diff-253bd1419aa0e1df7737a9ff6729ad6121c5dc1dc635b6aca8c7711c97853c42L195-R195

https://github.com/X-lab2017/oss101/pull/107/files#diff-253bd1419aa0e1df7737a9ff6729ad6121c5dc1dc635b6aca8c7711c97853c42L239-R239

https://github.com/X-lab2017/oss101/pull/107/files#diff-253bd1419aa0e1df7737a9ff6729ad6121c5dc1dc635b6aca8c7711c97853c42L239-R239

**Pull request merged**
