### PR TITLE
typo: `partdicular` at line 475, `poet` at line 383, `taat` at line 387

### PR DESCRIPTION
**Pull request by XDxc-cuber**
fixes
- fix wrong letter typo `poet` at line 383 to `post` @xbxj 
- fix wrong letter typo `taat` at line 387 to `that` @MartinZheng717 
- fix extra letter typo `partdicular` at line 475 to `particular` @duliaojason 
team 10205501417 10205501419 10205501454 10205501457

### CODE REVIEW

**Comment by XDxc-cuber** [comment]
@TieWay59 comment something XD

**Comment by TieWay59** [comment]
下面尝试把 [91879c3](https://github.com/X-lab2017/oss101/pull/154/commits/91879c3cf834be1d7725d10026200cea575a5e36) 这个commit去掉 @XDxc-cuber

**Comment by TieWay59** [comment]
别忘了这两处还需要再调整一下哦。

image

**Review by TieWay59 — APPROVED** [review]
LGTM

**Pull request merged**
