### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by abcdabcd3899**
Signed-off-by: @abcdabcd3899 @Kongbaimoon @@tyxtyxtyxtyx

### CODE REVIEW

**Comment by TieWay59** [comment]
FYI:


具体步骤如下：

1. 访问 <https://github.com/X-lab2017/oss101> ，队长 fork 本仓库。
   - 克隆到本地，创建 team-<队长学号> 的分支，作为团队的工作分支。
   - 队员 fork 队长的分支，也是采用 PR 的方式向队长分支提交 commit。结合所学，用 git 的方式协作。
2. 查看文件 `Assignments/assignment-typo.md`，阅读文件中的提示寻找 typo。
3. 修复 typo，并提交一个 PR。PR 的标题要以 《typo: `<typo原文>` at <行号>, ... 》作为标题，例如 typo: `xxx` at line 12, `xxx` at line 13, `xxx` at line 14，如果写不下，那么就缩减为：typo: at line 12, 13 and 16
   - PR 的内容要包括:
   - 列出修复的内容，例如：fix skip letter typoxxxat line 12 to yyy
   - 小组成员的成员的学号，例如： 5555903062 5555903063 5555903064 5555903065
4. 等待助教或老师审核 PR，并给出反馈，可能不会马上合并，所以要注意不要与已有的同学冲突。

请注意，typo 的类型只有以下几种（数量只作为估计）：

- Skip letter 20
- Extra letter 10
- Skip spaces 15
- Extra space 10
- Wrong letter 10

祝你们学习愉快！

---

UPD1:

如果是四个人的小队，可以由队长负责合并队员的PR，其他三人找 typo。这样每个人都可以参与到流程。

以下是一个更清晰 PR 正文的例子，请同学们参考：


<table>
  <tr>
    <td> markdown </td>
    <td> 预览 </td>
  </tr>
  <tr>
<td> 

```markdown
标题 typo: `peple` at line 27, `throu gh` at line 109

fix #71 

- fix extra space typo `throu gh` at line 109 to `through`
- fix skip letter typo `lbrary` at line 111 to `library`

team: 522759030XX 522759030XX
```

</td>
 <td>

标题 typo: `peple` at line 27, `throu gh` at line 109

fix #71 

- fix extra space typo `throu gh` at line 109 to `through`
- fix skip letter typo `lbrary` at line 111 to `library`

team: 522759030XX 522759030XX

 </td>
  </tr>
</table>


---

UPD2:

提醒一个常见问题，我们的文档中存在一种非空格的不可见字符 [Unicode Character 'NO-BREAK SPACE' (U+00A0)](https://www.fileformat.info/info/unicode/char/00a0/index.htm)，顾名思义，他是一种不折行的空格。

但非常不巧，它和我们常用的空格 [SPACE (U+0020)](https://www.fileformat.info/info/unicode/char/0020/index.htm) 是两种完全不同的符号。我观察到有部分同学的 commit 中，可能因为一些意外，导致这个符号被转换了。

进而导致引入了额外的变更。请各位同学和队长留心 review code diff，因为额外的变更在 diff 中是很显而易见的！一个人出现问题很正常，但两个人发现不了，就是流程有大意的体现。

---

UPD3:

关于占坑：我听说同学们的匆忙可能处于希望快速完成PR的冲动，但是实际上你们并不需要这么做，也没有很多PR是一蹴而就的，你们可以转换思路，先把typo找到，确认没问题，直接由队长分支发起PR，即使里面什么都还没有。不用担心，因为PR会和这个分支保持同步，你们先确认了要修复的内容，再由同学分工合入PR，是一样的。并且不必那么匆忙。

强调：先用 PR 绑定你的分支并且可以后面再改，没必要那么匆忙去完成所有流程。（也不用自己创建链接，因为PR内部就会链接所有相关的资源）

**Comment by abcdabcd3899** [comment]
> 修复 typo，并提交一个 PR。PR 的标题要以 《typo: `<typo原文>` at <行号>, ... 》作为标题，例如 typo: `xxx` at line 12, `xxx` at line 13, `xxx` at line 14，如果写不下，那么就缩减为：typo: at line 12, 13 and 16
> * PR 的内容要包括:
> * 列出修复的内容，例如：fix skip letter typoxxxat line 12 to yyy
> * 小组成员的成员的学号，例如： 5555903062 5555903063 5555903064 5555903065

In my opinion, the pr commit message does not need to be written in accordance with the line number of the original text. The pr commit message should be able to express the general meaning of this modification, which is one thing. If I add something else to the file that causes the line number to change, then the pr commit message is wrong, and that's the second thing. The pr file itself contains the correct location to modify the file.

**Comment by TieWay59** [comment]
> In my opinion,...

1. I can't understand in which case when fixing a typo of limited 5 types (hope you have read it carefully) would cause a new line or delete a line. If you have found the case, please let me know it.
2. I admit that this is a limited practice assignment for the specific course, and I intend to let students have an easier time on checking other PRs and avoiding conflicts. This is a choice to show kindness to others if you can manage to treat it as an assignment, which you can choose not to.
3. If you have this disagreement on the assignment sets, I think the best time to tell me is earlier after @will-ww's class which I believe you must attend. But you didn't tell me earlier, and now you tell me this after most of the students have followed the instructions. How will others feel if I now tell everybody that I have made the criterion lower for you? I can take it for sure, but I wonder if it's a good thing for you?
4. If you have read the assignment text, you would find a sentence "作业的评分标准如下：... 格式：PR 是否清晰，规范。", in case you don't understand, I mean the assignment PRs should be written in a clear and standard way since I have also provided templates.
5. You are right, the very greate point. If you are the first one I'll change the instructs. Whereas, how about taking consistency into account?

**Review by TieWay59 — COMMENTED** [review]
Good work, this PR will still be recognized as a normal PR since it's not related to our assignment criterion. It's welcomed, we always encourage more contributions to our class! ♥

I'm just reminding you that as course TA that you can always let me know if you have trouble understanding instructions or finding typos.

**Pull request closed without merging**
