### PR TITLE
typo: 'peple' at line 27, 'throu gh' at line 109, and 'lbrary' at line 111 to 'library'

### PR DESCRIPTION
**Pull request by wengsy150943**
fix #71 

- fix extra space typo 'throu gh' at line 109 to 'through'
- fix skip letter typo 'lbrary' at line 111 to 'library'
- fix skip letter typo 'peple' at line 27 to 'people'

team: 52275903002 51255903107 51255903009 51255903075

### CODE REVIEW

**Comment by will-ww** [comment]
> fix #71
> 
> * fix extra space typo 'throu gh' at line 109 to 'through'
> * fix skip letter typo 'lbrary' at line 111 to 'library'
> * fix skip letter typo 'peple' at line 27 to 'people'
> 
> team: 52275903002 51255903107 51255903009 51255903075

So quickly and great~

**Comment by qkgoalkeeper** [comment]
[c3c4280](https://github.com/X-lab2017/oss101/pull/72/commits/c3c42809b6f6573d1f50f239dc5852731e3b7f57)提交时的文字写错了，fix:skip letter peple line 12 to people应该为fix:skip letter peple line 27 to people

**Comment by TieWay59** [comment]
嘿，不用太担心，从我的角度来看，可以由 @qkgoalkeeper 仓库执行 rebase 把 @wengsy150943 的 commit skip 掉，然后由 @wengsy150943 重新提供新的变更。这个过程需要队长的分支强制提交，你们可以试试看，如果有其他方案的话，也可以按照你们的来。

**Comment by qkgoalkeeper** [comment]
> 嘿，不用太担心，从我的角度来看，可以由 @wengsy150943 仓库执行 rebase 把 @qkgoalkeeper 的 commit skip 掉，然后由 @qkgoalkeeper 重新提供新的变更。这个过程需要队长的分支强制提交，你们可以试试看，如果有其他方案的话，也可以按照你们的来。

已修改

**Review by TieWay59 — CHANGES_REQUESTED** [review]
Good Job😃

**Review by TieWay59 — APPROVED** [review]

**Pull request merged**
